name: CI

on:
  push:
    branches:    
      - master
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm install
    - run: npm test
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
       args: deploy --only hosting
      env:
       FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
